apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: geverghenodeexpress 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: geverghenodeexpress 
    spec:
      containers:
        - name: geverghenodeexpress 
          image: azuresaturdaydemo.azurecr.io/geverghenodeexpress
          ports:
          - containerPort: 8080